import type { SellIntelPayload } from "./types"

function mockComputedAt(): string {
  return new Date().toISOString()
}

export function getMockSellIntelPayload(): SellIntelPayload {
  return {
    aircraft: {
      make: "Piper",
      model: "PA-28-181 Archer",
      yearMin: 1980,
      yearMax: 1984,
      smoh: 890,
      askingPrice: 54000,
      panelType: "steam",
      avionicsSelected: ["Garmin GNS 430W", "ADS-B out"],
    },
    marketPosition: {
      medianAskPrice: 52000,
      p25AskPrice: 46500,
      p75AskPrice: 58500,
      activeListingCount: 14,
      avgDaysOnMarket: 67,
      priceVsMedianPercent: 3.8,
      demandTier: "MODERATE",
      topStates: [
        { state: "TX", count: 3 },
        { state: "FL", count: 2 },
        { state: "CA", count: 2 },
        { state: "AZ", count: 2 },
        { state: "CO", count: 1 },
      ],
      recentOwnershipChanges: 8,
      comps: [
        {
          id: "c1",
          year: 1982,
          make: "Piper",
          model: "PA-28-181",
          askingPrice: 49500,
          ttaf: 3800,
          smoh: 1100,
          location: "Dallas TX",
          daysOnMarket: 42,
          flipScore: 68,
          flipTier: "GOOD",
          url: null,
        },
        {
          id: "c2",
          year: 1981,
          make: "Piper",
          model: "PA-28-181",
          askingPrice: 53000,
          ttaf: 4100,
          smoh: 620,
          location: "Phoenix AZ",
          daysOnMarket: 28,
          flipScore: 72,
          flipTier: "GOOD",
          url: null,
        },
        {
          id: "c3",
          year: 1983,
          make: "Piper",
          model: "PA-28-181",
          askingPrice: 57500,
          ttaf: 2900,
          smoh: 310,
          location: "Tampa FL",
          daysOnMarket: 14,
          flipScore: 79,
          flipTier: "GOOD",
          url: null,
        },
        {
          id: "c4",
          year: 1980,
          make: "Piper",
          model: "PA-28-181",
          askingPrice: 47800,
          ttaf: 5200,
          smoh: 1450,
          location: "Denver CO",
          daysOnMarket: 91,
          flipScore: 61,
          flipTier: "FAIR",
          url: null,
        },
        {
          id: "c5",
          year: 1984,
          make: "Piper",
          model: "PA-28-181",
          askingPrice: 55900,
          ttaf: 2100,
          smoh: 450,
          location: "Houston TX",
          daysOnMarket: 19,
          flipScore: 74,
          flipTier: "GOOD",
          url: null,
        },
        {
          id: "c6",
          year: 1982,
          make: "Piper",
          model: "PA-28-181",
          askingPrice: 51200,
          ttaf: 4400,
          smoh: 890,
          location: "San Diego CA",
          daysOnMarket: 55,
          flipScore: 66,
          flipTier: "GOOD",
          url: null,
        },
      ],
      priceHistory: [
        { month: "2025-10", medianPrice: 50500, listingCount: 11 },
        { month: "2025-11", medianPrice: 51000, listingCount: 12 },
        { month: "2025-12", medianPrice: 50000, listingCount: 9 },
        { month: "2026-01", medianPrice: 52500, listingCount: 14 },
        { month: "2026-02", medianPrice: 53000, listingCount: 13 },
        { month: "2026-03", medianPrice: 52000, listingCount: 14 },
      ],
    },
    upgradeROI: {
      avionicsItems: [
        {
          name: "Garmin GTX 345 ADS-B",
          installCost: 3400,
          valueAdd: 4800,
          netROI: 1400,
          recommendation: "DO",
          rationale: "ADS-B In+Out adds $4,800 buyer premium. $1,400 net positive.",
        },
        {
          name: "Garmin G5 (HSI replacement)",
          installCost: 2800,
          valueAdd: 3200,
          netROI: 400,
          recommendation: "OPTIONAL",
          rationale: "Modest positive ROI. Improves appeal but not essential.",
        },
        {
          name: "Full paint",
          installCost: 12000,
          valueAdd: 5000,
          netROI: -7000,
          recommendation: "SKIP",
          rationale: "Full repaint rarely recovers cost. Detail clean instead (~$400).",
        },
        {
          name: "Engine overhaul (890 SMOH)",
          installCost: 20000,
          valueAdd: 11000,
          netROI: -9000,
          recommendation: "SKIP",
          rationale: "890 SMOH is mid-life. Overhaul at this stage loses ~$9,000.",
        },
      ],
      engineNarrative: {
        smoh: 890,
        tbo: 2000,
        pctRemaining: 55.5,
        framing:
          "890 SMOH — 1,110 hours of certified engine life remaining (Lycoming O-360, 2,000-hr TBO). Mid-life engine with no overhaul pressure.",
        buyerRiskLevel: "LOW",
        overhaulCostEstimate: 20000,
      },
      annualAdvice: {
        status: "fresh",
        recommendation:
          "Your fresh annual is a top-3 selling point. Lead with it in the listing headline. Buyers pay a $1,500–$2,500 premium.",
        estimatedCost: null,
      },
      damageHistoryImpact: null,
      bestSpendSummary:
        "Best spend before listing: GTX 345 ADS-B upgrade ($3,400 installed, +$1,400 net) + detail clean ($400). Skip paint and engine work entirely.",
      mustSkipItems: [
        "Engine overhaul — 890 SMOH is mid-life. Net loss ~$9,000.",
        "Full repaint — rarely recovers cost at this price point. Detail clean instead.",
      ],
      compsAvionicsFrequency: [
        { token: "ADS-B", count: 10, pctOfComps: 71.4 },
        { token: "WAAS GPS", count: 6, pctOfComps: 42.9 },
        { token: "autopilot", count: 4, pctOfComps: 28.6 },
      ],
      modelSpecificWarnings: ["PA-28 wing spar AD (2024) — confirm inspection status if applicable."],
      buyerExpectations: ["ADS-B out", "WAAS GPS", "working autopilot"],
      signatureUpgrade: "Garmin GTX 345 ADS-B",
    },
    listingStrategy: {
      suggestedListPrice: 54000,
      negotiationFloor: 50000,
      priceReductionSchedule: [
        { dayThreshold: 0, action: "List at $54,000. Hold firm for 30 days.", targetPrice: 54000 },
        { dayThreshold: 30, action: "Reduce to $51,500 if no serious inquiries.", targetPrice: 51500 },
        { dayThreshold: 60, action: "Reduce to $50,000 and offer to contribute to pre-buy.", targetPrice: 50000 },
        { dayThreshold: 90, action: "Reassess: consider broker or price at floor.", targetPrice: null },
      ],
      platforms: [
        {
          name: "Controller.com",
          url: "https://www.controller.com",
          priority: "PRIMARY",
          rationale: "Largest GA inventory. Best for serious buyers with financing.",
        },
        {
          name: "Trade-A-Plane",
          url: "https://www.trade-a-plane.com",
          priority: "PRIMARY",
          rationale: "Second largest. Strong broker presence.",
        },
        {
          name: "Barnstormers",
          url: "https://www.barnstormers.com",
          priority: "PRIMARY",
          rationale: "Best for cash buyers under $60K.",
        },
        {
          name: "ASO.com",
          url: "https://www.aso.com",
          priority: "SECONDARY",
          rationale: "Additional exposure, different buyer pool.",
        },
        {
          name: "AOPA Pilot Marketplace",
          url: "https://www.aopa.org",
          priority: "SECONDARY",
          rationale: "Reaches financially qualified AOPA members.",
        },
      ],
      keywords: [
        "fresh annual",
        "WAAS GPS",
        "ADS-B compliant",
        "ready to fly",
        "logs complete",
        "always hangared",
        "IFR equipped",
      ],
      photoGuide: [
        "3/4 front view in morning light — lead with this",
        "Full panel, engine running, all gauges visible",
        "Logbook stack — airframe, engine, prop spread open",
        "Engine bay — clean and accessible",
        "Interior: front seats and rear",
        "Left and right profiles",
        "Any recent work: annual signoff page, 337s",
      ],
      brokerVsSelf: {
        selfSellNetEstimate: 51300,
        brokerNetEstimate: 48735,
        breakEvenDaysOnMarket: 45,
        recommendation:
          "Market is moderately active — self-sell is viable. Save the ~$2,700 commission.",
      },
    },
    computedAt: mockComputedAt(),
    dataQuality: "strong",
  }
}
