import type { AcquisitionItem, UpgradeItem } from "@/lib/dealDesk/calculations";

export type DealDeskSeed = {
  listingId: string;
  aircraftLabel: string;
  sourceUrl: string;
  askingPrice: number;
  deferredMaintenance: number;
  engineReservePerHour?: number;
  make?: string;
  model?: string;
  /** Listing intelligence for wizard insights (Phase 5F). */
  daysOnMarket?: number | null;
  priceReduced?: boolean | null;
  /** Percent vs submodel median when present (e.g. +5 = 5% above). */
  vsMedianPricePct?: number | null;
  isSteamGauge?: boolean | null;
  hasGlassCockpit?: boolean | null;
  /** Listing score / risk signals for Live P&L health checklist. */
  riskLevel?: string | null;
  /** Primary displayed resale signal (intelligence v2+). */
  flipScore?: number | null;
  flipTier?: string | null;
  flipExplanation?: {
    p1_pricing_edge?: { pts?: number; max?: number };
    p2_airworthiness?: { pts?: number; max?: number };
    p3_improvement_room?: { pts?: number; max?: number };
    p4_exit_liquidity?: { pts?: number; max?: number };
    suppressed?: string;
    error?: string;
  } | null;
  avionicsScore?: number | null;
  /** Engine life remaining 0–1 (fraction) or 0–100 (percent) from `ev_pct_life_remaining`. */
  evPctLifeRemaining?: number | null;
  faaMatched?: boolean | null;
  /** Flattened score_data / listing columns for Live P&L drill-down. */
  engineScore?: number | null;
  propScore?: number | null;
  llpScore?: number | null;
  /** Legacy v1 pillars — omitted from UI when flip score is primary. */
  investmentScore?: number | null;
  marketOpportunityScore?: number | null;
  executionScore?: number | null;
  conditionScore?: number | null;
  pricingConfidence?: string | null;
  compSelectionTier?: string | null;
  compUniverseSize?: number | null;
  compExactCount?: number | null;
  compFamilyCount?: number | null;
  compMakeCount?: number | null;
  compMedianPrice?: number | null;
  compP25Price?: number | null;
  compP75Price?: number | null;
  mispricingZscore?: number | null;
  evExplanation?: string | null;
  evDataQuality?: string | null;
  evHoursSmoh?: number | null;
  evTboHours?: number | null;
  evHoursRemaining?: number | null;
  evScoreContribution?: number | null;
  intelligenceVersion?: string | null;
  hasAccidentHistory?: boolean | null;
  accidentCount?: number | null;
};

export type DealDeskScenarioWithContext = {
  id: string;
  listing_id: string;
  label: string;
  asking_price: number | null;
  deferred_maintenance: number;
  avionics_upgrade_budget: number;
  paint_interior_budget: number;
  ferry_flight_cost: number;
  hold_period_months: number;
  title_escrow_fees: number;
  insurance_estimate: number;
  total_acquisition_cost: number | null;
  estimated_resale_price: number | null;
  profit_at_ask: number | null;
  profit_percent_at_ask: number | null;
  target_profit_dollars: number;
  max_offer_price: number | null;
  acquisition_items: AcquisitionItem[];
  upgrade_items: UpgradeItem[];
  hangar_monthly: number;
  insurance_annual_premium: number;
  insurance_hull_value: number;
  insurance_liability_limit: string;
  insurance_deductible_pct: number;
  subscriptions_monthly: number;
  annual_inspection_reserve_monthly: number;
  admin_overhead_monthly: number;
  planned_hours_flown: number;
  fuel_gph: number;
  fuel_price_per_gallon: number;
  oil_cost_per_hour: number;
  engine_reserve_per_hour: number;
  prop_reserve_per_hour: number;
  misc_maintenance_per_hour: number;
  financing_enabled: boolean;
  loan_amount: number;
  down_payment: number;
  interest_rate_pct: number;
  loan_term_years: number;
  loan_origination_fees: number;
  opportunity_cost_rate_pct: number;
  broker_commission_pct: number;
  exit_escrow_fees: number;
  presale_spruce_up: number;
  buyer_squawk_contingency_pct: number;
  exit_sales_tax_pct: number;
  days_to_sell_base: number;
  days_to_sell_slow: number;
  sale_price_low_pct: number;
  sale_price_stretch_pct: number;
  maintenance_contingency_pct: number;
  resale_base: number | null;
  resale_low: number | null;
  resale_stretch: number | null;
  all_in_basis: number | null;
  total_carrying_costs: number | null;
  total_variable_costs: number | null;
  total_financing_cost_over_hold: number | null;
  net_proceeds_after_exit: number | null;
  net_profit_base: number | null;
  net_profit_low: number | null;
  net_profit_stretch: number | null;
  roi_pct_base: number | null;
  annualized_roi_pct_base: number | null;
  breakeven_sale_price: number | null;
  max_purchase_price_for_target_roi: number | null;
  source_listing_url: string | null;
  aircraft_label: string | null;
  created_at: string;
  updated_at: string;
  listing_context?: {
    asking_price?: number | null;
    deferred_total?: number | null;
    source_url?: string | null;
  } | null;
};
