export type AircraftListing = {
  id: string
  title: string | null
  year: number | null
  make: string | null
  model: string | null
  source: string | null
  source_id: string | null
  url: string | null
  listing_url: string | null
  price_asking: number | null
  asking_price: number | null
  value_score: number | null
  engine_score: number | null
  prop_score: number | null
  llp_score: number | null
  avionics_score: number | null
  avionics_installed_value: number | null
  total_modification_value: number | null
  stc_market_value_premium_total: number | null
  has_glass_cockpit: boolean | null
  is_steam_gauge: boolean | null
  avionics_matched_items: Array<{ item?: string; value?: number }> | null
  stc_modifications: Array<{ stc_name?: string; premium_value?: number }> | null
  risk_level: string | null
  deal_rating: number | null
  deal_tier: string | null
  vs_median_price: number | null
  comps_sample_size: number | null
  deal_comparison_source: string | null
  deferred_total: number | null
  true_cost: number | null
  intelligence_version: string | null
  location_city: string | null
  location_state: string | null
  location_label: string | null
  n_number: string | null
  is_active: boolean | null
  days_on_market: number | null
  first_seen_date: string | null
  last_seen_date: string | null
  price_reduced: boolean | null
  price_reduced_date: string | null
  price_reduction_amount: number | null
  serial_number: string | null
  primary_image_url: string | null
  image_urls: string[] | null
  logbook_urls: string[] | null
  listing_fingerprint: string | null
  faa_registration_alert: string | null
  accident_count: number | null
  most_recent_accident_date: string | null
  most_severe_damage: string | null
  has_accident_history: boolean | null
  description: string | null
  description_full: string | null
  total_time_airframe: number | null
  engine_time_since_overhaul: number | null
  time_since_overhaul: number | null
  engine_tbo_hours: number | null
  time_since_new_engine: number | null
  time_since_prop_overhaul: number | null
}
