ALTER TABLE aircraft_listings
  ADD COLUMN IF NOT EXISTS faa_owner TEXT,
  ADD COLUMN IF NOT EXISTS faa_city TEXT,
  ADD COLUMN IF NOT EXISTS faa_state TEXT,
  ADD COLUMN IF NOT EXISTS faa_cert_date TEXT,
  ADD COLUMN IF NOT EXISTS faa_status TEXT,
  ADD COLUMN IF NOT EXISTS faa_matched BOOLEAN DEFAULT FALSE;
