-- Reference tables for aircraft intelligence (TBO and life-limited parts).
-- reference_service.py queries these; in-code fallback used when tables are empty or missing.
-- Run in Supabase SQL Editor.

-- Engine TBO: pattern is matched after normalization (e.g. O320, LYCOMING IO360).
-- Longest matching pattern wins. Add DEFAULT row for fallback.
CREATE TABLE IF NOT EXISTS engine_tbo_reference (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pattern text NOT NULL,
  tbo_hours integer NOT NULL DEFAULT 2000,
  calendar_years integer,
  cost_min integer DEFAULT 25000,
  cost_max integer DEFAULT 45000,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_engine_tbo_pattern ON engine_tbo_reference (pattern);

COMMENT ON TABLE engine_tbo_reference IS 'TBO and cost range by engine pattern; pattern matched after normalize (alphanumeric uppercase)';

-- Propeller TBO
CREATE TABLE IF NOT EXISTS propeller_tbo_reference (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pattern text NOT NULL,
  tbo_hours integer NOT NULL DEFAULT 2000,
  calendar_years integer,
  cost_min integer DEFAULT 5000,
  cost_max integer DEFAULT 15000,
  notes text,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_prop_tbo_pattern ON propeller_tbo_reference (pattern);

COMMENT ON TABLE propeller_tbo_reference IS 'TBO and cost range by propeller make/pattern';

-- Life-limited parts: applicable is null (all aircraft) or e.g. ROBINSON, CIRRUS.
CREATE TABLE IF NOT EXISTS life_limited_parts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_type text NOT NULL,
  interval_months integer,
  interval_hours integer,
  cost_min integer NOT NULL DEFAULT 0,
  cost_max integer NOT NULL DEFAULT 0,
  unairworthy_if_overdue boolean DEFAULT true,
  applicable text,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_llp_item_type ON life_limited_parts (item_type);
CREATE INDEX IF NOT EXISTS idx_llp_applicable ON life_limited_parts (applicable);

COMMENT ON TABLE life_limited_parts IS 'LLP rules; applicable null = all, or e.g. ROBINSON, CIRRUS';

-- Seed engine fallbacks (for greenfield; skip if you already have data)
INSERT INTO engine_tbo_reference (pattern, tbo_hours, calendar_years, cost_min, cost_max)
VALUES
  ('LYCOMING O-360', 2000, NULL, 25000, 45000),
  ('LYCOMING IO-360', 2000, NULL, 25000, 45000),
  ('LYCOMING O-320', 2000, NULL, 25000, 45000),
  ('LYCOMING IO-320', 2000, NULL, 25000, 45000),
  ('LYCOMING O-540', 2000, NULL, 25000, 45000),
  ('LYCOMING IO-540', 2000, NULL, 25000, 45000),
  ('LYCOMING IO-550', 2000, NULL, 25000, 45000),
  ('LYCOMING TIO-540', 1800, NULL, 25000, 45000),
  ('LYCOMING', 2000, 12, 25000, 45000),
  ('CONTINENTAL IO-550', 2000, NULL, 25000, 45000),
  ('CONTINENTAL IO-520', 1700, NULL, 25000, 45000),
  ('CONTINENTAL O-470', 1500, NULL, 25000, 45000),
  ('CONTINENTAL IO-470', 1500, NULL, 25000, 45000),
  ('CONTINENTAL', 1800, 12, 25000, 45000),
  ('ROTAX 912', 2000, 5, 15000, 25000),
  ('ROTAX', 2000, 5, 15000, 25000),
  ('PT6A', 3500, NULL, 80000, 150000),
  ('TPE331', 3500, NULL, 80000, 150000),
  ('DEFAULT', 2000, 12, 25000, 45000);

-- Seed propeller fallbacks
INSERT INTO propeller_tbo_reference (pattern, tbo_hours, calendar_years, cost_min, cost_max, notes)
VALUES
  ('MCCAULEY', 2000, 6, 5000, 15000, NULL),
  ('HARTZELL', 2000, 6, 5000, 15000, NULL),
  ('SENSENICH', 6000, NULL, 5000, 12000, 'on-condition possible'),
  ('DEFAULT', 2000, 6, 5000, 15000, NULL);

-- Seed LLP rules (upsert by item_type)
ALTER TABLE life_limited_parts DROP CONSTRAINT IF EXISTS life_limited_parts_item_type_key;
ALTER TABLE life_limited_parts ADD CONSTRAINT life_limited_parts_item_type_key UNIQUE (item_type);
INSERT INTO life_limited_parts (item_type, interval_months, interval_hours, cost_min, cost_max, unairworthy_if_overdue, applicable)
VALUES
  ('annual_inspection', 12, NULL, 2000, 5000, true, NULL),
  ('elt_battery', 12, NULL, 200, 500, true, NULL),
  ('caps_repack', 120, NULL, 15000, 20000, true, 'CIRRUS'),
  ('magneto_500hr', NULL, 500, 800, 2000, false, NULL),
  ('robinson_12yr', 144, 12000, 80000, 120000, true, 'ROBINSON')
ON CONFLICT (item_type) DO UPDATE SET
  interval_months = EXCLUDED.interval_months,
  interval_hours = EXCLUDED.interval_hours,
  cost_min = EXCLUDED.cost_min,
  cost_max = EXCLUDED.cost_max,
  unairworthy_if_overdue = EXCLUDED.unairworthy_if_overdue,
  applicable = EXCLUDED.applicable;
