-- Capture richer Controller detail-page fields, including twin-engine/prop fields.
-- Keep this migration additive and safe for repeated environments.

ALTER TABLE public.aircraft_listings
  ADD COLUMN IF NOT EXISTS controller_specs_flat jsonb,
  ADD COLUMN IF NOT EXISTS controller_specs_groups jsonb,
  ADD COLUMN IF NOT EXISTS listing_condition text,
  ADD COLUMN IF NOT EXISTS flight_rules text,
  ADD COLUMN IF NOT EXISTS based_at text,
  ADD COLUMN IF NOT EXISTS complete_logs boolean,
  ADD COLUMN IF NOT EXISTS inspection_status text,
  ADD COLUMN IF NOT EXISTS has_air_conditioning boolean,
  ADD COLUMN IF NOT EXISTS oxygen_system boolean,
  ADD COLUMN IF NOT EXISTS flight_into_known_icing boolean,
  ADD COLUMN IF NOT EXISTS inadvertent_ice_protection boolean,
  ADD COLUMN IF NOT EXISTS additional_equipment_text text,
  ADD COLUMN IF NOT EXISTS year_painted integer,
  ADD COLUMN IF NOT EXISTS year_interior integer,
  ADD COLUMN IF NOT EXISTS interior_configuration text,
  ADD COLUMN IF NOT EXISTS avionics_flight_deck text,
  ADD COLUMN IF NOT EXISTS avionics_waas boolean,
  ADD COLUMN IF NOT EXISTS avionics_svt boolean,
  ADD COLUMN IF NOT EXISTS avionics_active_traffic boolean,
  ADD COLUMN IF NOT EXISTS avionics_terrain_warning boolean,
  ADD COLUMN IF NOT EXISTS engine_1_model text,
  ADD COLUMN IF NOT EXISTS engine_1_time_text text,
  ADD COLUMN IF NOT EXISTS engine_1_time_hours numeric,
  ADD COLUMN IF NOT EXISTS engine_1_tbo_hours numeric,
  ADD COLUMN IF NOT EXISTS engine_1_notes text,
  ADD COLUMN IF NOT EXISTS engine_2_model text,
  ADD COLUMN IF NOT EXISTS engine_2_time_text text,
  ADD COLUMN IF NOT EXISTS engine_2_time_hours numeric,
  ADD COLUMN IF NOT EXISTS engine_2_tbo_hours numeric,
  ADD COLUMN IF NOT EXISTS engine_2_notes text,
  ADD COLUMN IF NOT EXISTS prop_1_manufacturer text,
  ADD COLUMN IF NOT EXISTS prop_1_model text,
  ADD COLUMN IF NOT EXISTS prop_1_time_text text,
  ADD COLUMN IF NOT EXISTS prop_1_time_hours numeric,
  ADD COLUMN IF NOT EXISTS prop_2_manufacturer text,
  ADD COLUMN IF NOT EXISTS prop_2_model text,
  ADD COLUMN IF NOT EXISTS prop_2_time_text text,
  ADD COLUMN IF NOT EXISTS prop_2_time_hours numeric,
  ADD COLUMN IF NOT EXISTS prop_blade_count integer,
  ADD COLUMN IF NOT EXISTS prop_notes text;
